/** Login Mutations types**/
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

/**Authentication Mutation types**/
export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const REGISTER_FAILED = 'REGISTER_FAILED';

/** User profile Mutation types **/
export const PROFILE = 'PPROFILE';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_FAILED = 'PROFILE_FAILED';
export const PROFILE_ERROR = 'PROFILE_ERROR';

/** User profile update mutation types **/
export const PROFILE_UPDATE = 'PROFILE_UPDATE';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const PROFILE_UPDATE_FAILED = 'PROFILE_UPDATE_FAILED';
export const PROFILE_UPDATE_ERROR = 'PROFILE_UPDATE_ERROR';

/** Repayment Schedule Mutation types **/
export const REPAYMENT_SCHEDULE = 'REPAYMENT_SCHEDULE';
export const REPAYMENT_SCHEDULE_SUCCESS = 'REPAYMENT_SCHEDULE_SUCCESS';
export const REPAYMENT_SCHEDULE_ERROR = ' REPAYMENT_SCHEDULE_ERROR ';
export const REPAYMENT_SCHEDULE_FAILED = 'REPAYMENT_SCHEDULE_FAILED';

export const REPAYMENT_SCHEDULES = 'REPAYMENT_SCHEDULES';
export const REPAYMENT_SCHEDULES_SUCCESS = 'REPAYMENT_SCHEDULES_SUCCESS ';
export const REPAYMENT_SCHEDULES_ERROR = ' REPAYMENT_SCHEDULES_ERROR';
export const REPAYMENT_SCHEDULES_FAILED = 'REPAYMENT_SCHEDULES_FAILED';
