/** Login Mutations types**/
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

/**Authentication Mutation types**/
export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const REGISTER_FAILED = 'REGISTER_FAILED';

/** User profile Mutation types **/
export const PROFILE = 'PPROFILE';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_FAILED = 'PROFILE_FAILED';
export const PROFILE_ERROR = 'PROFILE_ERROR';

/** User profile update mutation types **/
export const PROFILE_UPDATE = 'PROFILE_UPDATE';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const PROFILE_UPDATE_FAILED = 'PROFILE_UPDATE_FAILED';
export const PROFILE_UPDATE_ERROR = 'PROFILE_UPDATE_ERROR';

/** Repayment Schedule Mutation types **/
export const REPAYMENT_SCHEDULE = 'REPAYMENT_SCHEDULE';
export const REPAYMENT_SCHEDULE_SUCCESS = 'REPAYMENT_SCHEDULE_SUCCESS';
export const REPAYMENT_SCHEDULE_ERROR = ' REPAYMENT_SCHEDULE_ERROR ';
export const REPAYMENT_SCHEDULE_FAILED = 'REPAYMENT_SCHEDULE_FAILED';

export const REPAYMENT_SCHEDULES = 'REPAYMENT_SCHEDULES';
export const REPAYMENT_SCHEDULES_SUCCESS = 'REPAYMENT_SCHEDULES_SUCCESS ';
export const REPAYMENT_SCHEDULES_ERROR = ' REPAYMENT_SCHEDULES_ERROR';
export const REPAYMENT_SCHEDULES_FAILED = 'REPAYMENT_SCHEDULES_FAILED';


export const SAVE_REPAYMENT_SCHEDULE = 'SAVE_REPAYMENT_SCHEDULE';
export const SAVE_REPAYMENT_SCHEDULE_SUCCESS = 'SAVE_REPAYMENT_SCHEDULE_SUCCESS';
export const SAVE_REPAYMENT_SCHEDULE_ERROR = 'SAVE_REPAYMENT_SCHEDULE_ERROR ';
export const SAVE_REPAYMENT_SCHEDULE_FAILED = 'SAVE_REPAYMENT_SCHEDULE_FAILED';


/** Client/User posts Mutation types **/

export const POST_NEW_BLOG_CONTENT = "POST_NEW_BLOG_CONTENT";
export const POST_NEW_BLOG_CONTENT_SUCCESS = "POST_NEW_BLOG_CONTENT_SUCCESS";
export const POST_NEW_BLOG_CONTENT_FAILED = "POST_NEW_BLOG_CONTENT_FAILED";
export const POST_NEW_BLOG_CONTENT_ERROR = "POST_NEW_BLOG_CONTENT_ERROR";

export const GET_BLOG_POSTS = "GET_BLOG_POSTS";
export const GET_BLOG_POSTS_SUCCESS = "GET_BLOG_POSTS_SUCCESS";
export const GET_BLOG_POSTS_FAILED = "GET_BLOG_POSTS_FAILED";
export const GET_BLOG_POSTS_ERROR = "GET_BLOG_POSTS_ERROR";

export const EDIT_BLOG_POST = "EDIT_BLOG_POST";
export const EDIT_BLOG_POST_SUCCESS = "EDIT_BLOG_POST_SUCCESS";
export const EDIT_BLOG_POST_FAILED = "EDIT_BLOG_POST_FAILED";
export const EDIT_BLOG_POST_ERROR = "EDIT_BLOG_POST_ERROR";

export const DELETE_BLOG_POST = "DELETE_BLOG_POST";
export const DELETE_BLOG_POST_SUCCESS = "DELETE_BLOG_POST_SUCCESS";
export const DELETE_BLOG_POST_FAILED = "DELETE_BLOG_POST_FAILED";
export const DELETE_BLOG_POST_ERROR = "DELETE_BLOG_POST_ERROR";

export const COMMENT_BLOG_POST = "COMMENT_BLOG_POST";
export const COMMENT_BLOG_POST_SUCCESS = "COMMENT_BLOG_POST_SUCCESS";
export const COMMENT_BLOG_POST_FAILED = "COMMENT_BLOG_POST_FAILED";
export const COMMENT_BLOG_POST_ERROR = "COMMENT_BLOG_POST_ERROR";


/** Sample mutation definition **/
export const POST_INDICATOR_VALUEx = "POST_INDICATOR_VALUEx";
export const POST_INDICATOR_VALUEx_SUCCESS = "POST_INDICATOR_VALUEx_SUCCESS";
export const POST_INDICATOR_VALUEx_FAILED = "POST_INDICATOR_VALUEx_FAILED";
export const POST_INDICATOR_VALUEx_ERROR = "POST_INDICATOR_VALUEx_ERROR";

